# theme = "tokyonight_storm"
# theme = "base16_transparent"
theme = "gruvbox_transparent"
# theme = "tokyonight_moon_transparent"

[editor]
line-number = "relative"
mouse = false
auto-format = true
true-color = true

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[keys.normal]
C-s = ":w!"
C-w = ":buffer-close"
y = [":clipboard-yank", "yank"]

[keys.insert]
C-s = [":w!", "normal_mode"]
C-w = [":buffer-close", "normal_mode"]

[keys.select]
y = [":clipboard-yank", "yank"]
