# Zinit home location
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Install Zinit if not already installed
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"

# Source the zinit file
source "${ZINIT_HOME}/zinit.zsh"

# Env Vars
export PATH="$HOME/.local/bin:$PATH"
export ZDOTDIR="$HOME"
export EDITOR="vim"

# ZSH plugins
zi light zsh-users/zsh-syntax-highlighting
zi light zsh-users/zsh-autosuggestions
zi light Aloxaf/fzf-tab

# ZSH completions
zi ice as"completion"; zi snippet OMZP::docker/completions/_docker
zi ice as"completion"; zi snippet OMZP::docker-compose/_docker-compose

# Usefull plugins
zi snippet OMZP::sudo
zi snippet OMZP::command-not-found

# Load completions
autoload -Uz compinit && compinit

zi cdreplay -q

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'

# Alias
alias ls="ls --color"
alias hx="helix"
alias rz="source $ZDOTDIR/.zshrc"
alias ez="$EDITOR $ZDOTDIR/.zshrc"

# Fzf with zsh
eval "$(fzf --zsh)"

# Zoxide with zsh
eval "$(zoxide init --cmd cd zsh)"

# Starship with zsh
eval "$(starship init zsh)" 

# ---------------------- AUTOGENERATED CODE ---------------------- #
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Turso
export PATH="$PATH:/home/bhuvansh/.turso"

# pnpm
export PNPM_HOME="/home/bhuvansh/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
